mode: dev

defaults:
  denyUnknownTools: true
  unknownToolAction: DENY
  log: debug
  redaction: standard
  injection:
    mode: shadow

risk:
  read: ALLOW
  write: ALLOW
  critical: ASK

tools:
  - name: read
    risk: read
  - name: write
    risk: write
  - name: edit
    risk: write
  - name: apply_patch
    risk: write
  - name: exec
    risk: critical
    useExecApprovals: true
  - name: process
    risk: critical
  - name: agents_list
    risk: read
  - name: browser
    risk: write
  - name: canvas
    risk: read
  - name: cron
    risk: write
  - name: gateway
    risk: critical
    action: DENY
  - name: image
    risk: read
  - name: message
    risk: write
  - name: nodes
    risk: critical
  - name: session_status
    risk: read
  - name: sessions_history
    risk: read
  - name: sessions_list
    risk: read
  - name: sessions_send
    risk: write
  - name: sessions_spawn
    risk: critical
  - name: tts
    risk: read
  - name: web_fetch
    risk: read
  - name: web_search
    risk: read
  - name: memory_search
    risk: read
  - name: memory_get
    risk: read
